- name: Clone git repo and install python application
  hosts: webserver
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: Copy nginx config file
      copy:
        src: flaskapp.conf
        dest: /etc/nginx/sites-enabled/flaskapp
        owner: root
        group: root
      notify: restart nginx

    - name: restart nginx
      service: name=nginx state=restarted enabled=yes
    #
    - name: Transfer the script
      script: installApp.sh
