- name: Clone git repo and install python application
  hosts: webserver
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: Ensure ntp is enabled on boot
      become: yes
      command: systemctl enable ntp

    - name: set the max "open files" limit across all users/processes, soft & hard, to 65535
      pam_limits:
        domain: "*"
        limit_type: "{{item.limit_type}}"
        limit_item: "{{item.limit_item}}"
        value: "{{item.value}}"
      with_items:
        - { limit_type: 'soft', limit_item: 'nofile', value: 65535 }
        - { limit_type: 'hard', limit_item: 'nofile', value: 65535 }

    - name: reload settings from all system configuration files
      shell: sysctl --system

    - name: Copy nginx config file
      copy:
        src: flaskapp.conf
        dest: /etc/nginx/sites-enabled/flaskapp
        owner: root
        group: root
        mode: 755

    - name: Transfer the script
      script: installApp.sh

    - name: restart nginx
      service: name=nginx state=restarted enabled=yes

    - name: Change the working directory to flaskapp and run the flaskapp using gunicorn3.
      shell: gunicorn3 tiny_app:app &
      args:
        chdir: /flaskapp
