- name: Clone git repo and install python application
  hosts: webserver
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: Ensure ntp is enabled on boot
      become: yes
      command: systemctl enable ntp

    - name: Copy nginx config file
      copy:
        src: flaskapp.conf
        dest: /etc/nginx/sites-enabled/flaskapp
        owner: root
        group: root
        mode: 755

    - name: Transfer the script
      script: installApp.sh

    - name: restart nginx
      service: name=nginx state=restarted enabled=yes

    - name: Change the working directory to flaskapp and run the flaskapp using gunicorn3.
      shell: gunicorn3 tiny_app:app &
      args:
        chdir: /flaskapp
